### PR TITLE
Magritte Integration

### PR DESCRIPTION
**Pull request by seandenigris**

### CODE REVIEW

**Comment by svenvc** [comment]
Thanks Sean for the contribution.

It is good that this is a pure add-on in a separate package with extensions.

However, even with that packaging, if someone loads the code, it will seem as if there is only one way of doing things (i.e. using MADescriptions).

If it were me, I would qualify the selectors on NeoCSVReader and Object further. For example change #addFieldDescribedBy: to addFieldDescribedByMagritte: or change #fromCSVFile: to #fromCSVFileUsingMagritte:

Do you understand my point ?

Personally I almost never add such 'global' 'convenience' methods since they either force or suggest a single way of doing things, while there are often many more options.

What do you think ?

**Comment by seandenigris** [comment]
I agree! Thanks for the input. It started as a private extension so I didn’t think of it. I’ll make the changes.

**Comment by svenvc** [comment]
Thanks again, Sean.

**Comment by seandenigris** [comment]
No problem! I'm thinking I'd like to write some tests, but how do you handle test packaging for optional packages. Is there a convention?

**Comment by svenvc** [comment]
Good idea.

I am not sure about the naming, just use your best judgment  ;-)

**Pull request merged**
